1_8:
  BLOCK_CHEST_OPEN: CHEST_OPEN
  ENTITY_EXPERIENCE_ORB_PICKUP: ORB_PICKUP
  ENTITY_ITEM_PICKUP: ITEM_PICKUP
  UI_BUTTON_CLICK: CLICK

legacy:
  LIME_TERRACOTTA: STAINED_CLAY:5
  RED_TERRACOTTA: STAINED_CLAY:14
  GRAY_STAINED_GLASS_PANE: STAINED_GLASS_PANE:7
  SPAWNER: MOB_SPAWNER
  ZOMBIE_HEAD: SKULL_ITEM:2
  SKELETON_SKULL: SKULL_ITEM
  BEEF: RAW_BEEF
  PORKCHOP: PORK
  POTATO: POTATO_ITEM
  CARROT: CARROT_ITEM
  SKELETON_SPAWN_EGG: MONSTER_EGG:51
  ZOMBIE_SPAWN_EGG: MONSTER_EGG:54
  CREEPER_SPAWN_EGG: MONSTER_EGG:50
  SPIDER_SPAWN_EGG: MONSTER_EGG:52
  PIG_SPAWN_EGG: MONSTER_EGG:90
  COW_SPAWN_EGG: MONSTER_EGG:92
  SHEEP_SPAWN_EGG: MONSTER_EGG:91
  CHICKEN_SPAWN_EGG: MONSTER_EGG:93
