name: SpawnerCollectors
version: 1.8.3
description: Store mob spawners in a "cloud gui" instead of creating laggy spawner farms
api-version: 1.13
main: me.bestem0r.spawnercollectors.SCPlugin
softdepend: [HeadDatabase, Essentials, CMI, AdvancedSpawners, MineableSpawners, SilkSpawners, PlaceholderAPI]
depend: [Vault]
commands:
  sc:
    usage: /sc <spawners/mobs/reload>
    aliases: [spawnercollectors]
permissions:
  spawnercollectors.command.reload:
    description: Use /sc reload
    default: op
  spawnercollectors.command.mobs:
    description: Open your mob storage
    default: op
  spawnercollectors.command.spawners:
    description: Open your spawners storage
    default: op
  spawnercollectors.command.open:
    description: Open other's spawner/mob storage
    default: op
  spawnercollectors.command.givespawner:
    description: Give spawners
    default: op
  spawnercollectors.sell:
    description: Sell collected mobs
    default: op
  spawnercollectors.auto_sell:
    description: Enable auto-sell
    default: op
  spawnercollectors.withdraw.mob:
    description: Withdraw mobs
    default: op
  spawnercollectors.withdraw.spawner:
    description: Withdraw spawners
    default: op
  spawnercollectors.receive_xp:
    description: Receive XP if more_permissions is enabled
    default: op
  spawnercollectors.bypass_place:
    description: Bypass spawner place restriction
    default: op
  spawnercollectors.bypass_limit:
    description: Bypass spawner max limit
    default: op


